AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false

Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 50
